#pragma once
// GLM functions will expect radian angles for all its functions
#define GLM_FORCE_RADIANS
// Expect depths buffer to range from 0 to 1. (opengl depth buffer ranges from -1 to 1)
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <string>
#include <map>
#include "engine/bagel_engine_device.hpp"

namespace bagel
{
	// Magic hash function from boost, modified to return same value for same vertex
	inline void Hash(std::size_t &seed, const float &v)
	{
		// std::hash<T> hasher;
		seed ^= static_cast<uint32_t>(v) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
	};
	struct SubmeshInfo
	{
		uint32_t firstIndex = 0;
		uint32_t indexCount = 0;
		uint32_t firstVertex = 0;
		uint32_t vertexCount = 0;
		uint32_t materialIndex = 0;
		bool transparentMaterial = false;
	};

	// Per-vertex skinning influence, packed to 8 bytes. NOT part of BGLModel::Vertex —
	// it lives in a parallel array that becomes a GPU SSBO read by the skinned shader via
	// skinData[skinBase + gl_VertexIndex]. The static vertex format is untouched.
	//   joints[i]  = joint index (into the skeleton's palette); glTF caps influences at 4.
	//   weights[i] = unorm8 blend weight (255 == 1.0). Default: full weight on joint 0.
	struct SkinInfluence
	{
		uint8_t joints[4]{0, 0, 0, 0};
		uint8_t weights[4]{255, 0, 0, 0};
	};

	struct GLTFMaterial
	{
		std::string name;
		uint16_t albedoMap = 0;
		uint16_t normalMap = 0;
		uint16_t metalRoughMap = 0;
		uint16_t specularMap = 0;
		uint16_t heightMap = 0;
		uint16_t opacityMap = 0;
		uint16_t aoMap = 0;
		uint16_t refractionMap = 0;
		uint16_t emissionMap = 0;
	};

	// Serializable texture-source paths for a material. The bindless handles in
	// BGLModel::Material are transient (rebuilt per run), so for GENERATED models — whose
	// materials are assigned in code rather than loaded from an asset file — we
	// persist the source paths instead and re-load them on map rehydrate. Empty
	// strings mean "no map for that slot". OBJ/GLTF models leave this unused; their
	// materials come back from the asset via the loader.
	struct MaterialSource
	{
		std::string albedo;
		std::string normal;
		std::string metalRough;
		std::string emission;
	};

	// Model-related Component Build Mode
	// Determines the vertex buffer layout
	enum ComponentBuildMode
	{
		FACES,
		LINES
	};

	struct ModelLoadSettings
	{
		std::string source;
		float scale = 1.0f;
		glm::vec3 scaleVec = {1.0f, 1.0f, 1.0f};
		ComponentBuildMode buildMode = ComponentBuildMode::FACES;
		uint32_t maxPrimitives = UINT32_MAX;
		// bool isDynamic = false; //dynamic models are allocated in host-visible vertex/index buffer. Host can edit the vertex data real time

		bool isDeformable = false; // if the vertices can be moved around by cpu (vertex animation)
		bool isDynamic = false;	   // if the faces can be regenerated by cpu
		// When true (default) all solid/opaque geometry is merged into a single submesh.
		// When false, each source mesh's solid geometry is kept as its own submesh — useful
		// for large models where one merged submesh would be too big. Transparent geometry is
		// always split per source mesh regardless of this setting.
		bool mergeSolidSubmeshes = true;
		ModelLoadSettings() = default;
		ModelLoadSettings(ComponentBuildMode mode) : buildMode(mode) {}
	};

	// SkeletonData / JointTransform / AnimationClip live in animation/bagel_animation.hpp
	// (included above) — the loader fills them, the animation module consumes them.
	// ComponentBuildMode and ModelLoadSettings now live in model_load_settings.hpp
	// (included above) so ModelComponent can store/serialize the load recipe.
	namespace BGLModel
	{
		struct Material
		{
			// bindless texture indices — 0 means unused. Only the 4 maps the shaders sample.
			uint16_t albedoMap = 0;
			uint16_t normalMap = 0;
			uint16_t metalRoughMap = 0; // G=roughness, B=metallic (glTF ORM convention)
			uint16_t emissionMap = 0;
		};
		struct Vertex
		{
			glm::vec3 position;
			glm::vec3 color;
			glm::vec3 normal;
			glm::vec4 tangent{0.0f, 0.0f, 0.0f, 1.0f}; // xyz = tangent, w = bitangent handedness sign (+1 or -1)
			glm::vec2 uv;

			// Index into the global material table (BGLMaterialManager). The vertex shader
			// resolves it to the actual bindless texture handles. 0 = the all-unused material.
			uint16_t materialIndex = 0;
			static std::vector<VkVertexInputBindingDescription> getBindingDescriptions();
			static std::vector<VkVertexInputAttributeDescription> getAttributeDescriptions();
		};

		struct VertexHasher
		{
			size_t operator()(const Vertex &a) const
			{
				size_t seed{};
				Hash(seed, a.position.x);
				Hash(seed, a.position.y);
				Hash(seed, a.position.z);
				Hash(seed, a.normal.x);
				Hash(seed, a.normal.y);
				Hash(seed, a.normal.z);
				return seed;
			}
		};

		// We assume that two vertices with same vertex normal and same uv coordinate at same position are same vertices
		struct VertexEquals
		{
			bool operator()(const Vertex &a, const Vertex &b) const
			{
				return std::tie(
						   a.position.x, a.position.y, a.position.z,
						   a.normal.x, a.normal.y, a.normal.z,
						   a.uv.x, a.uv.y) == std::tie(b.position.x, b.position.y, b.position.z,
													   b.normal.x, b.normal.y, b.normal.z,
													   b.uv.x, b.uv.y);
			}
		};
	};

	// A loaded model's shared, immutable-after-build data: GPU geometry buffers, submesh
	// layout, model-space bounds, and skin-table metadata. Owned by ModelCacheManager and
	// keyed by source path — every entity that uses the same model points at ONE Model
	// (flyweight), so the heavy data exists once and an entity's destruction never frees it.
	// The cache frees these (vkDestroyBuffer) on scene unload / shutdown, GPU idle.
	struct Model
	{
		static constexpr uint32_t MAX_SUBMESHES = 128;
		// A model has at most this many distinct materials, shared across its submeshes
		// (each Submesh::materialIndex selects one).
		static constexpr uint32_t MAX_MATERIALS = 8;

		struct Submesh
		{
			uint32_t firstIndex = 0;
			uint32_t indexCount = 0;
			uint32_t firstVertex = 0;
			uint32_t vertexCount = 0;
			uint32_t materialIndex = 0;
			glm::vec3 aabbMin{0.0f};
			glm::vec3 aabbMax{0.0f};
		};

		// Lightweight contiguous view over a [begin,end) run of submeshes (C++17, no <span>).
		struct SubmeshRange
		{
			const Submesh *b;
			const Submesh *e;
			const Submesh *begin() const { return b; }
			const Submesh *end() const { return e; }
			uint32_t size() const { return static_cast<uint32_t>(e - b); }
			bool empty() const { return b == e; }
		};

		// The build recipe that produced this model, and its identity (loadSettings.source is
		// the cache key). Everything below is rebuilt from it by the model loader.
		ModelLoadSettings loadSettings{};

		Submesh submeshes[MAX_SUBMESHES]{};
		uint32_t submeshCount = 0;
		// Submeshes are stored solid-first: [0, solidSubmeshCount) are solid/opaque and
		// [solidSubmeshCount, submeshCount) are transparent — one split index filters by
		// transparency at draw time.
		uint32_t solidSubmeshCount = 0;

		// Skin table block (rebuilt by the loader). The material for a draw is
		//   skinTable[ skinBase + skinIndex*numSlots + vertex.materialIndex(=local slot) ].
		// These describe the model's block; skinIndex is per-entity (on ModelComponent).
		uint16_t skinBase = 0;
		uint16_t numSlots = 1;
		uint8_t numSkins = 1;

		// Skeletal skinning. isSkinned models are drawn by the dedicated AnimatedGBufferRenderSystem
		// and skipped by the static passes. skinVertexBase is this model's base offset into the
		// global per-vertex skin-influence SSBO; the shader reads v[skinVertexBase + gl_VertexIndex].
		bool isSkinned = false;
		uint32_t skinVertexBase = 0;

		glm::vec3 aabbMin{0.0f};
		glm::vec3 aabbMax{0.0f};

		// GPU handles — OWNED by this Model, freed in the destructor. Null-safe defaults so a
		// half-built Model is safe to destroy (vkDestroyBuffer/vkFreeMemory on null are no-ops).
		VkBuffer vertexBuffer = VK_NULL_HANDLE;
		VkBuffer indexBuffer = VK_NULL_HANDLE;
		VkDeviceMemory vertexMemory = VK_NULL_HANDLE;
		VkDeviceMemory indexMemory = VK_NULL_HANDLE;
		void *mappedVB = nullptr; // host-visible vertex buffer mapped here (dynamic/deformable)
		void *mappedIB = nullptr; // host-visible index buffer mapped here

		uint32_t indexCount = 0;
		uint32_t vertexCount = 0;

		// Solid/opaque submeshes — drawn in the G-buffer (deferred) pass.
		SubmeshRange solidSubmeshes() const { return {submeshes, submeshes + solidSubmeshCount}; }
		// Transparent submeshes — drawn in the forward alpha-blended pass.
		SubmeshRange transparentSubmeshes() const { return {submeshes + solidSubmeshCount, submeshes + submeshCount}; }
		bool hasTransparent() const { return solidSubmeshCount < submeshCount; }

		// One Model per source, owned by the cache via unique_ptr — never copied or moved
		// (that would alias or double-free the GPU handles). Destroying it frees the buffers.
		Model() = default;
		Model(const Model &) = delete;
		Model &operator=(const Model &) = delete;
		Model(Model &&) = delete;
		Model &operator=(Model &&) = delete;
		~Model()
		{
			vkDestroyBuffer(BGLDevice::device(), vertexBuffer, nullptr);
			vkDestroyBuffer(BGLDevice::device(), indexBuffer, nullptr);
			vkFreeMemory(BGLDevice::device(), vertexMemory, nullptr);
			vkFreeMemory(BGLDevice::device(), indexMemory, nullptr);
		}
	};

	// Parsed "<model>.yaml" sidecar describing in-game properties of a model. First property:
	// model skins (Source's $texturegroup / skin families).
	//
	// YAML schema:
	//   materials:                 # named MaterialSource definitions (engine-relative paths)
	//     body_red: { albedo: "/materials/body_red.png", normal: "/materials/body_n.png" }
	//     head_red: { albedo: "/materials/head_red.png" }
	//   skins:                     # rows = skins (skin 0 = default); slot index -> material name
	//     - {}                     # skin 0: all model defaults
	//     - { 0: body_red, 4: head_red }   # skin 1: override slots 0 and 4
	//     - { 0: body_blue }                # skin 2
	// A slot a skin doesn't list keeps the model's own (glTF/OBJ) material.
	//   ik:                        # two-bone IK chains, referenced by BONE NAME (skeleton joint
	//     - thigh: root            # node name). One list entry == one IKSetup.
	//       shin:  knee
	//       foot:  foot
	//       goal:  target          # bone the foot reaches for
	//       pole:  ik              # bone hinting the bend direction
	//       weight: 1.0            # optional (default 1.0)
	//       enabled: true          # optional (default true)
	//   attachments:               # named attach points ($attachment analog), bone-relative
	//     - name:   muzzle
	//       bone:   foot           # skeleton bone the point rides
	//       offset: [0, 1, 0]      # position in the bone's local space
	//       rotate: [0, 0, 0]      # optional Euler XYZ in DEGREES (default 0)
	struct ModelSidecar
	{
		// One IK chain as authored in the sidecar: bone NAMES (resolved to joint indices later,
		// once the skeleton's names are known — see ModelLoaderBase::resolveIkSetups).
		struct IkChain
		{
			std::string thigh, shin, foot, goal, pole;
			float weight = 1.0f;
			bool enabled = true;
		};

		// One attach point ($attachment analog): a name, the bone it rides (NAME, resolved later),
		// and a local offset (position + Euler rotation, radians) within that bone's space.
		struct Attachment
		{
			std::string name;
			std::string bone;
			glm::vec3 offset{0.0f};
			glm::vec3 rotate{0.0f}; // Euler XYZ, radians
		};

		// skins[skinIndex][slot] = override MaterialSource. Missing slot => model default.
		// skins.empty() => only the implicit default skin.
		std::vector<std::map<uint32_t, MaterialSource>> skins;
		std::vector<IkChain> ikChains;		 // authored IK chains (empty => none)
		std::vector<Attachment> attachments; // authored attach points (empty => none)

		uint32_t numSkins() const { return skins.empty() ? 1u : static_cast<uint32_t>(skins.size()); }

		// Look for the sibling ".yaml" of an engine-relative model source path
		// (e.g. "/models/x.gltf" -> "/models/x.yaml"). Returns empty (numSkins()==1) if the
		// file is absent or fails to parse.
		static ModelSidecar loadForModel(const std::string &modelSourcePath);
	};
}