#pragma once

// Lightweight, dependency-free definition of the model "recipe": the settings that
// fully describe how to (re)build a model from its source asset. Pulled out of
// bagel_model_loader.hpp so ModelComponent (in bagel_ecs_components.hpp) can store
// and serialize it without dragging in xatlas / the texture loader.

#include <cstdint>
#include <string>

#include <glm/glm.hpp>

namespace bagel {

	//Model-related Component Build Mode
	//Determines the vertex buffer layout
	enum ComponentBuildMode {
		FACES,
		LINES
	};

	struct ModelLoadSettings {
		std::string source;
		float scale = 1.0f;
		glm::vec3 scaleVec = { 1.0f, 1.0f, 1.0f };
		ComponentBuildMode buildMode = ComponentBuildMode::FACES;
		uint32_t maxPrimitives = UINT32_MAX;
		//bool isDynamic = false; //dynamic models are allocated in host-visible vertex/index buffer. Host can edit the vertex data real time

		bool isDeformable = false; // if the vertices can be moved around by cpu (vertex animation)
		bool isDynamic = false; // if the faces can be regenerated by cpu
		// When true (default) all solid/opaque geometry is merged into a single submesh.
		// When false, each source mesh's solid geometry is kept as its own submesh — useful
		// for large models where one merged submesh would be too big. Transparent geometry is
		// always split per source mesh regardless of this setting.
		bool mergeSolidSubmeshes = true;
		ModelLoadSettings() = default;
		ModelLoadSettings(ComponentBuildMode mode) : buildMode(mode) {}
	};

}
